eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}-${random.int}
        hostname: localhost

spring:
    application:
        name: calculator

server:
    port: 0
